### ISSUE TITLE
where is the planar data？

### ISSUE THREAD

**Issue by maraple8** [harryjo97/GruM#2]
I couldn't find the planar dataset under './GruM-master/GruM_2D/data/' folder
how can I get it?
thanks

![微信截图_20240908140814](https://github.com/user-attachments/assets/764567af-5dde-4688-9bfd-97c558926f0a)

**Comment by harryjo97** [comment]
The Planar dataset (planar_64_200.pt) can be found in the following link: https://drive.google.com/drive/folders/13esonTpioCzUAYBmPyeLSjXlDoemXXQB?usp=sharing

Please refer to `Dataset preparations` section of `/GruM_2D/README.md`
